title: Node.js client for object stores like AWS S3, GCP GCS or Minio

markdown: kramdown

baseurl: /object-storage-js
destination: ../build/docs
remote_theme: pmarsceill/just-the-docs@v0.2.8

search_enabled: false

exclude:
  - Gemfile
  - vendor
